export const GET_IMAGE_CODE = 'GET_IMAGE_CODE'
export const SET_DAPP_STATUS_OF_BROWSER_SUCCESS = 'SET_DAPP_STATUS_OF_BROWSER_SUCCESS'
export const SET_DAPP_IS_READY_SUCCESS = 'SET_DAPP_IS_READY_SUCCESS'
export const SET_DAPP_IS_INSTALL_METAMASK_SUCCESS = 'SET_DAPP_IS_INSTALL_METAMASK_SUCCESS'
